### ISSUE TITLE
Update version.

### ISSUE THREAD

**Issue by leech001** [aleksanderlech/armv7-docker-compose#1]
Please update you version.

**Comment by aleksanderlech** [comment]
Hello,

Can you please be more specific?

**Comment by leech001** [comment]
> Hello,
> 
> Can you please be more specific?

No. I don't use anything specific. It's just that when the repository isn't updated you start thinking that it's an abandoned project :(

**Comment by aleksanderlech** [comment]
I have no way of testing it now but I updated to aleksjej/armv7-docker-compose:1.26.2 you can check if you want
